baseurl = "https://deathbytangents.com" # Controls base URL
languageCode = "en-US" # Controls site language
title = "Death By Tangents" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating
theme = "after-dark" # Set default theme

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "â†©" # Provides a nicer footnote return link

[params]
  author = "Richard Boyd II" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits
  images = [
    "https://richardboydii.com/img/profile.jpg"
  ] # Suggested, controls default Open Graph images
  theme_variant = "hack dark-grey" # Optional, for use to overriding default theme

  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Personal Site"
    weight = 4
    identifier = "site"
    url = "https://richardboydii.com"